[package]
name = "wgpu_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
winit = "0.29.0"
wgpu = "0.18.0"
futures = "0.3.18"

[build-dependencies]
shaderc = "0.8.3"
