import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import axios from "axios"

// axios.defaults.baseURL = "http:127.0.0.1:8000"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
